# Background info

## Network

LKYGSPP

1. [Ajay Tandon](https://blogs.worldbank.org/team/ajay-tandon), is currently Lead Economist with the World Bank based in Washington, DC. He works on several countries including most recently on India, Indonesia, Bhutan, Laos, and the Philippines. He received a PhD in economics (80s) from Virginia Tech with a dissertation that focused on the intersection of macroeconomics and population dynamics. Previously, over 2004-2007, he worked with the research department of the Asian Development Bank in Manila where he worked on issues related to human development. He also worked with the Evidence and Information for Policy department of the World Health Organization in Geneva from 1998-2003, primarily on measurement challenges including those related to correcting biases in self-reported responses in household survey data and on [health system performance (this paper)](https://pages.stern.nyu.edu/~wgreene/Statistics/WHO-COMP-Study-30.pdf). He has held visiting research appointments at both Oxford University and Harvard University. He has written several publications on the issues of statistical methodology, health systems efficiency, health financing, domestic resource mobilization, and universal health coverage. He is co-author of several books, including most recently of ‘Going Universal: How 24 Countries Are Implementing Universal Health Coverage from the Bottom-up’.
1. [Reem Hafez (Winnie 的学生)](https://blogs.worldbank.org/team/reem-hafez), joined the Health, Nutrition, and Population Global Practice at the World Bank as a Senior Economist in September 2016. She has 12 years’ experience working on international health policy, health financing, and health system reform issues. Her current research interests include governance and accountability in decentralized contexts, efficiency measurement, and the use of health care analytics to inform decision making. 

## Geography

[Central asia](https://www.worldbank.org/en/region/eap)

1. comprises 

## Health system knowledge

[Health system strengthening](https://en.wikipedia.org/wiki/Health_systems_strengthening)

It is structured around the WHO framework that describes health systems in terms of six core components or “building blocks”: 

1. health workforce, 
1. financing 
    - financing and the health workforce are key **input** components to the health system 
1. service delivery, 
1. access to essential medicines, 
    - service delivery and medical products and technologies, reflects the **outputs** of the health system, i.e. the availability and distribution of care
1. leadership/governance 
1. health information systems
    - leadership/governance and health information systems, provide the **basis** for the overall policy and regulation of all the other health system blocks

[Health financing](https://www.who.int/health-topics/health-financing#tab=tab_1)

Health financing is a core function of health systems that can enable progress towards universal health coverage by improving effective service coverage and financial protection. 

[Health service delivery](https://www.euro.who.int/en/health-topics/Health-systems/health-services-delivery)

A healthcare service delivery model is an approach to delivering healthcare. It's a series of services that include health services and support for the community, like education about preventive care and health promotion.
It has three major components: primary healthcare, health promotion and wellness, and caregiver education.

[UHC](https://en.wikipedia.org/wiki/Universal_health_care)

Universal health care (also called universal health coverage, universal coverage, or universal care) is a health care system in which all residents of a particular country or region are assured access to health care.

resilience of health system

The health system need to develop capacities to cope with challenges from both certainty and uncertainty
